version: 1.0.{build}
platform: x64
clone_folder: c:\project\src\github.com\dontpanic92\wxGo
clone_depth: 5
environment:
  matrix:
  - GOROOT: c:\go16
  - GOROOT: c:\go17
  - GOROOT: c:\go18

matrix:
  allow_failures:
    - GOROOT: c:\go16

build_script:
- cmd: >-

    set GOPATH=c:\project\

    set PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%GOROOT%\bin;%PATH%

    go env

    go version

    echo %APPVEYOR_BUILD_FOLDER%

    cd %APPVEYOR_BUILD_FOLDER%

    go get -v -t -x .\\...

